filePath = '_api/Term.lua' pastebinPath = 'HqTmrdQH' if not fs.exists(filePath) then shell.run(string.format('pastebin get %s %s', pastebinPath, filePath)) end loadfile(filePath)()
filePath = '_api/String.lua' pastebinPath = '5Dke2dac' if not fs.exists(filePath) then shell.run(string.format('pastebin get %s %s', pastebinPath, filePath)) end loadfile(filePath)()
filePath = '_objects/Monitor.lua' pastebinPath = 'SzRXq9K5' if not fs.exists(filePath) then shell.run(string.format('pastebin get %s %s', pastebinPath, filePath)) end loadfile(filePath)()
filePath = '_objects/Liquid.lua' pastebinPath = 'v6zavc5F' if not fs.exists(filePath) then shell.run(string.format('pastebin get %s %s', pastebinPath, filePath)) end loadfile(filePath)()
filePath = '_objects/Tank.lua' pastebinPath = 'phfyupC0' if not fs.exists(filePath) then shell.run(string.format('pastebin get %s %s', pastebinPath, filePath)) end loadfile(filePath)()
filePath = '_objects/Block.lua' pastebinPath = 'vuk7qm5e' if not fs.exists(filePath) then shell.run(string.format('pastebin get %s %s', pastebinPath, filePath)) end loadfile(filePath)()
filePath = 'main.lua' pastebinPath = 'BsJzNhkw' if not fs.exists(filePath) then shell.run(string.format('pastebin get %s %s', pastebinPath, filePath)) end loadfile(filePath)()
